using System;
using System.IO;
using System.Linq;
using Xunit;
using ZDD.Net.Core;
using ZDD.Net.Frontier;
using ZDD.Net.Graphs;
using ZDD.Net.Io;
using ZDD.Net.Specs;
using ZDD.Net.Tests.Stress;

namespace ZDD.Net.Tests.Io
{
    /// <summary>
    /// M5-2 completion criteria (issue #54): reading real Graphillion output produces the exact
    /// same family (fixtures under <c>TestData/Graphillion/</c>, generated by
    /// <c>generate_fixtures.py</c> against Graphillion 2.1 — see that directory's own comments),
    /// round-tripping this library's own output preserves the family, the elem/level direction
    /// mapping is correct (checked with families that are <i>not</i> symmetric under reversing
    /// variable order — a symmetric family couldn't catch a reversed mapping), and malformed input
    /// always throws <see cref="ZddFormatException"/> instead of crashing or misreading.
    /// </summary>
    public class GraphillionTextFormatTests : IClassFixture<DeepZdd>
    {
        private readonly DeepZdd _deep;

        public GraphillionTextFormatTests(DeepZdd deep) => _deep = deep;

        // ---- Fixtures: real Graphillion output ----

        [Fact]
        public void ReadsTheTriangleFixtureExactly()
        {
            // {{e1, e3}, {e2}} over a 3-element universe (traversal='as-is': e1/e2/e3 are elem
            // 1/2/3 in this order) — asymmetric, so getting the elem<->item direction backwards
            // would read back a different family, not just a relabeled version of the same one.
            string text = ReadFixture("triangle_family.zdd.txt");

            Zdd family = GraphillionTextFormat.Read(text, variableCount: 3);
            using ZddManager manager = family.Manager;

            Assert.Equal(3, manager.VariableCount);
            Assert.Equal(2, family.Count);
            AssertSetsEqual(new[] { new[] { 1 }, new[] { 0, 2 } }, family.Sets());
        }

        [Fact]
        public void ReadingTheTriangleFixtureInfersVariableCountWhenNotSupplied()
        {
            string text = ReadFixture("triangle_family.zdd.txt");

            Zdd family = GraphillionTextFormat.Read(text);
            using ZddManager manager = family.Manager;

            // The file's own elem values never exceed 3, so that's what gets inferred.
            Assert.Equal(3, manager.VariableCount);
            AssertSetsEqual(new[] { new[] { 1 }, new[] { 0, 2 } }, family.Sets());
        }

        [Fact]
        public void ReadingTheTriangleFixtureWithALargerExplicitVariableCountKeepsTheSameSets()
        {
            string text = ReadFixture("triangle_family.zdd.txt");

            Zdd family = GraphillionTextFormat.Read(text, variableCount: 5);
            using ZddManager manager = family.Manager;

            Assert.Equal(5, manager.VariableCount);
            AssertSetsEqual(new[] { new[] { 1 }, new[] { 0, 2 } }, family.Sets());
        }

        [Fact]
        public void ReadingTheTriangleFixtureWithATooSmallExplicitVariableCountThrows()
        {
            string text = ReadFixture("triangle_family.zdd.txt");

            ZddFormatException ex = Assert.Throws<ZddFormatException>(
                () => GraphillionTextFormat.Read(text, variableCount: 2));
            Assert.Contains("3", ex.Message);
        }

        [Fact]
        public void ReadsTheGridPathsFixtureMatchingAnIndependentlyBuiltZddNetFamily()
        {
            // Same 3x2 grid, same 0-based vertex numbering and edge order as generate_fixtures.py's
            // grid_3x2_paths() (Graph.Grid's own edge order matches it exactly — see that
            // function's docstring), so item i on both sides names the same edge.
            Graph grid = Graph.Grid(3, 2);
            Assert.Equal(7, grid.EdgeCount);

            string text = ReadFixture("grid_3x2_paths.zdd.txt");
            Zdd fromGraphillion = GraphillionTextFormat.Read(text, variableCount: grid.EdgeCount);
            using ZddManager fromGraphillionManager = fromGraphillion.Manager;

            using ZddManager builtManager = new ZddManager(grid.EdgeCount);
            Zdd builtDirectly = FrontierBuilder.Build<PathSpec>(builtManager, new PathSpec(grid, 0, grid.VertexCount - 1));

            Assert.Equal(4, fromGraphillion.Count);
            Assert.Equal(builtDirectly.Count, fromGraphillion.Count);

            int[][] expected = builtDirectly.Sets().Select(s => (int[])s.Clone()).ToArray();
            AssertSetsEqual(expected, fromGraphillion.Sets());
        }

        // ---- Round trip: this library's own writer feeding its own reader ----

        [Fact]
        public void RoundTripsAnEmptyFamily()
        {
            using ZddManager manager = new ZddManager(3);
            AssertRoundTripsToTheSameFamily(manager.Empty);
        }

        [Fact]
        public void RoundTripsABaseFamily()
        {
            using ZddManager manager = new ZddManager(3);
            AssertRoundTripsToTheSameFamily(manager.Base);
        }

        [Fact]
        public void RoundTripsAnAsymmetricHandBuiltFamily()
        {
            using ZddManager manager = new ZddManager(3);

            // {{0}, {1, 2}}: not symmetric under reversing item order (which would give {{2}, {0, 1}}).
            Zdd twelve = manager.CreateNode(2, lo: manager.Empty, hi: manager.Base);
            Zdd oneTwo = manager.CreateNode(1, lo: manager.Empty, hi: twelve);
            Zdd family = manager.CreateNode(0, lo: oneTwo, hi: manager.Base);

            AssertRoundTripsToTheSameFamily(family);
        }

        [Fact]
        public void RoundTripsALargeAsymmetricPathFamily()
        {
            // A non-square grid keeps the path family from being symmetric under reversing item order.
            Graph grid = Graph.Grid(4, 6);
            using ZddManager manager = new ZddManager(grid.EdgeCount);
            Zdd paths = FrontierBuilder.Build<PathSpec>(manager, new PathSpec(grid, 0, grid.VertexCount - 1));

            Assert.True(paths.Count > 1000);
            AssertRoundTripsToTheSameFamily(paths);
        }

        [Fact]
        public void RoundTripsADeepZddWithoutStackOverflow() =>
            AssertRoundTripsToTheSameFamily(_deep.Full);

        [Fact]
        public void DumpsMatchesWriteToATextWriter()
        {
            using ZddManager manager = new ZddManager(2);
            Zdd family = manager.Singleton(0);

            string viaDumps = GraphillionTextFormat.Write(family);

            using StringWriter writer = new StringWriter();
            GraphillionTextFormat.Write(family, writer);

            Assert.Equal(writer.ToString(), viaDumps);
        }

        [Fact]
        public void TrivialFamiliesDumpAsTheirTerminalTokenAloneWithATerminator()
        {
            using ZddManager manager = new ZddManager(2);

            Assert.Equal("B\n.\n", GraphillionTextFormat.Write(manager.Empty));
            Assert.Equal("T\n.\n", GraphillionTextFormat.Write(manager.Base));
        }

        // ---- Malformed input: never crashes, always ZddFormatException ----

        [Fact]
        public void WriteThrowsForDefaultZdd() =>
            Assert.Throws<InvalidOperationException>(() => GraphillionTextFormat.Write(default));

        [Fact]
        public void WriteThrowsForNullWriter()
        {
            using ZddManager manager = new ZddManager(1);
            Assert.Throws<ArgumentNullException>(() => GraphillionTextFormat.Write(manager.Empty, null!));
        }

        [Fact]
        public void WriteThrowsForDisposedManager()
        {
            ZddManager manager = new ZddManager(1);
            Zdd family = manager.Empty;
            manager.Dispose();

            Assert.Throws<ObjectDisposedException>(() => GraphillionTextFormat.Write(family, new StringWriter()));
        }

        [Fact]
        public void ReadThrowsForNullReader() =>
            Assert.Throws<ArgumentNullException>(() => GraphillionTextFormat.Read((TextReader)null!));

        [Fact]
        public void ReadThrowsForNullText() =>
            Assert.Throws<ArgumentNullException>(() => GraphillionTextFormat.Read((string)null!));

        [Fact]
        public void ReadThrowsForNegativeVariableCount() =>
            Assert.Throws<ArgumentOutOfRangeException>(() => GraphillionTextFormat.Read("B\n.\n", variableCount: -1));

        [Fact]
        public void ReadThrowsOnEmptyInput() =>
            AssertThrowsFormatException(string.Empty);

        [Fact]
        public void ReadThrowsWhenTheDumpIsNotTerminated() =>
            AssertThrowsFormatException("2 1 B T\n");

        [Fact]
        public void ReadThrowsWhenANodeLineHasTheWrongFieldCount() =>
            AssertThrowsFormatException("2 1 B\n.\n");

        [Fact]
        public void ReadThrowsWhenTheIdIsNotAnInteger() =>
            AssertThrowsFormatException("x 1 B T\n.\n");

        [Fact]
        public void ReadThrowsWhenElemIsNotAPositiveInteger() =>
            AssertThrowsFormatException("2 0 B T\n.\n");

        [Fact]
        public void ReadThrowsOnAForwardReferencingChild() =>
            // Node 2's hi child (3) is never defined.
            AssertThrowsFormatException("2 1 B 3\n.\n");

        [Fact]
        public void ReadThrowsWhenHiIsTheBottomTerminal() =>
            AssertThrowsFormatException("2 1 B B\n.\n");

        [Fact]
        public void ReadThrowsWhenAChildIsNotStrictlyCloserToTheLeavesThanItsParent()
        {
            // Node 3 (elem 1, i.e. closest to the root) references node 2 (elem 1 too) as its hi
            // child — children must have a *larger* elem (farther from the root) than their parent.
            AssertThrowsFormatException("2 1 B T\n3 1 B 2\n.\n");
        }

        [Fact]
        public void ReadThrowsWhenElemExceedsAnExplicitVariableCount()
        {
            ZddFormatException ex = Assert.Throws<ZddFormatException>(
                () => GraphillionTextFormat.Read("2 3 B T\n.\n", variableCount: 2));
            Assert.Contains("3", ex.Message);
        }

        [Fact]
        public void ReadTreatsBlankLinesAsIgnorable()
        {
            Zdd family = GraphillionTextFormat.Read("\n\n2 1 B T\n\n.\n\n", variableCount: 1);
            using ZddManager manager = family.Manager;
            Assert.Equal(1, family.Count);
        }

        [Fact]
        public void ReadThrowsWhenThereAreNoLinesBeforeTheTerminator() =>
            AssertThrowsFormatException(".\n");

        // ---- Helpers ----

        private static void AssertRoundTripsToTheSameFamily(in Zdd original)
        {
            ZddManager originalManager = original.Manager;

            string text = GraphillionTextFormat.Write(original);
            Zdd restored = GraphillionTextFormat.Read(text, originalManager.VariableCount);
            using ZddManager restoredManager = restored.Manager;

            Assert.Equal(originalManager.VariableCount, restoredManager.VariableCount);
            Assert.Equal(original.Count, restored.Count);

            int[][] originalSets = original.Sets().Select(s => (int[])s.Clone()).ToArray();
            AssertSetsEqual(originalSets, restored.Sets());
        }

        private static void AssertSetsEqual(int[][] expected, System.Collections.Generic.IEnumerable<int[]> actual)
        {
            string[] expectedKeys = expected.Select(SetKey).OrderBy(k => k, StringComparer.Ordinal).ToArray();
            string[] actualKeys = actual.Select(SetKey).OrderBy(k => k, StringComparer.Ordinal).ToArray();
            Assert.Equal(expectedKeys, actualKeys);
        }

        private static string SetKey(int[] set) => string.Join(",", set.OrderBy(x => x));

        private static ZddFormatException AssertThrowsFormatException(string text) =>
            Assert.Throws<ZddFormatException>(() => GraphillionTextFormat.Read(text));

        private static string ReadFixture(string fileName) =>
            File.ReadAllText(Path.Combine(RepositoryRoot(), "tests", "ZDD.Net.Tests", "TestData", "Graphillion", fileName));

        /// <summary>Walks up from the test assembly's location to find the repository root (same technique as <c>DependencyPolicyTests</c>).</summary>
        private static string RepositoryRoot()
        {
            DirectoryInfo? directory = new DirectoryInfo(AppContext.BaseDirectory);

            while (directory is not null)
            {
                if (File.Exists(Path.Combine(directory.FullName, "ZDD.Net.sln")))
                {
                    return directory.FullName;
                }

                directory = directory.Parent;
            }

            throw new InvalidOperationException($"Could not find ZDD.Net.sln above '{AppContext.BaseDirectory}'.");
        }
    }
}
